name: Examen-workflow

on:
   push:
     branches:
      - nueva_caracteristica

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Descargar code
        uses: actions/checkout@v5

      - name: Crear entorno python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Instalar pytest
        run: pip install pytest

      - name: Realizar test
        run: python test.py

      - name: Crear imagen dockerfile
        uses: docker/build-push-action@v6
        with:
          push: False
